sudo: false
language: ruby
rvm:
  - 2.1.6
cache: bundler
script:
  - bundle exec rspec
branches:
  except:
    - /^production_release_\d+$/
    - /^staging_release_\d+$/
notifications:
  email: false
